// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s (
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        data_16_val,
        data_17_val,
        data_18_val,
        data_19_val,
        data_20_val,
        data_21_val,
        data_22_val,
        data_23_val,
        data_24_val,
        data_25_val,
        data_26_val,
        data_27_val,
        data_28_val,
        data_29_val,
        data_30_val,
        data_31_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31
);


output   ap_ready;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
input  [15:0] data_5_val;
input  [15:0] data_6_val;
input  [15:0] data_7_val;
input  [15:0] data_8_val;
input  [15:0] data_9_val;
input  [15:0] data_10_val;
input  [15:0] data_11_val;
input  [15:0] data_12_val;
input  [15:0] data_13_val;
input  [15:0] data_14_val;
input  [15:0] data_15_val;
input  [15:0] data_16_val;
input  [15:0] data_17_val;
input  [15:0] data_18_val;
input  [15:0] data_19_val;
input  [15:0] data_20_val;
input  [15:0] data_21_val;
input  [15:0] data_22_val;
input  [15:0] data_23_val;
input  [15:0] data_24_val;
input  [15:0] data_25_val;
input  [15:0] data_26_val;
input  [15:0] data_27_val;
input  [15:0] data_28_val;
input  [15:0] data_29_val;
input  [15:0] data_30_val;
input  [15:0] data_31_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;
output  [15:0] ap_return_16;
output  [15:0] ap_return_17;
output  [15:0] ap_return_18;
output  [15:0] ap_return_19;
output  [15:0] ap_return_20;
output  [15:0] ap_return_21;
output  [15:0] ap_return_22;
output  [15:0] ap_return_23;
output  [15:0] ap_return_24;
output  [15:0] ap_return_25;
output  [15:0] ap_return_26;
output  [15:0] ap_return_27;
output  [15:0] ap_return_28;
output  [15:0] ap_return_29;
output  [15:0] ap_return_30;
output  [15:0] ap_return_31;

wire   [0:0] icmp_ln45_fu_400_p2;
wire   [14:0] trunc_ln42_53_fu_396_p1;
wire   [14:0] datareg_fu_406_p3;
wire   [0:0] icmp_ln45_23_fu_418_p2;
wire   [14:0] trunc_ln42_52_fu_392_p1;
wire   [14:0] datareg_23_fu_424_p3;
wire   [0:0] icmp_ln45_24_fu_436_p2;
wire   [14:0] trunc_ln42_51_fu_388_p1;
wire   [14:0] datareg_24_fu_442_p3;
wire   [0:0] icmp_ln45_25_fu_454_p2;
wire   [14:0] trunc_ln42_50_fu_384_p1;
wire   [14:0] datareg_25_fu_460_p3;
wire   [0:0] icmp_ln45_26_fu_472_p2;
wire   [14:0] trunc_ln42_49_fu_380_p1;
wire   [14:0] datareg_26_fu_478_p3;
wire   [0:0] icmp_ln45_27_fu_490_p2;
wire   [14:0] trunc_ln42_48_fu_376_p1;
wire   [14:0] datareg_27_fu_496_p3;
wire   [0:0] icmp_ln45_28_fu_508_p2;
wire   [14:0] trunc_ln42_47_fu_372_p1;
wire   [14:0] datareg_28_fu_514_p3;
wire   [0:0] icmp_ln45_29_fu_526_p2;
wire   [14:0] trunc_ln42_46_fu_368_p1;
wire   [14:0] datareg_29_fu_532_p3;
wire   [0:0] icmp_ln45_30_fu_544_p2;
wire   [14:0] trunc_ln42_45_fu_364_p1;
wire   [14:0] datareg_30_fu_550_p3;
wire   [0:0] icmp_ln45_31_fu_562_p2;
wire   [14:0] trunc_ln42_44_fu_360_p1;
wire   [14:0] datareg_31_fu_568_p3;
wire   [0:0] icmp_ln45_32_fu_580_p2;
wire   [14:0] trunc_ln42_43_fu_356_p1;
wire   [14:0] datareg_32_fu_586_p3;
wire   [0:0] icmp_ln45_33_fu_598_p2;
wire   [14:0] trunc_ln42_42_fu_352_p1;
wire   [14:0] datareg_33_fu_604_p3;
wire   [0:0] icmp_ln45_34_fu_616_p2;
wire   [14:0] trunc_ln42_41_fu_348_p1;
wire   [14:0] datareg_34_fu_622_p3;
wire   [0:0] icmp_ln45_35_fu_634_p2;
wire   [14:0] trunc_ln42_40_fu_344_p1;
wire   [14:0] datareg_35_fu_640_p3;
wire   [0:0] icmp_ln45_36_fu_652_p2;
wire   [14:0] trunc_ln42_39_fu_340_p1;
wire   [14:0] datareg_36_fu_658_p3;
wire   [0:0] icmp_ln45_37_fu_670_p2;
wire   [14:0] trunc_ln42_38_fu_336_p1;
wire   [14:0] datareg_37_fu_676_p3;
wire   [0:0] icmp_ln45_38_fu_688_p2;
wire   [14:0] trunc_ln42_37_fu_332_p1;
wire   [14:0] datareg_38_fu_694_p3;
wire   [0:0] icmp_ln45_39_fu_706_p2;
wire   [14:0] trunc_ln42_36_fu_328_p1;
wire   [14:0] datareg_39_fu_712_p3;
wire   [0:0] icmp_ln45_40_fu_724_p2;
wire   [14:0] trunc_ln42_35_fu_324_p1;
wire   [14:0] datareg_40_fu_730_p3;
wire   [0:0] icmp_ln45_41_fu_742_p2;
wire   [14:0] trunc_ln42_34_fu_320_p1;
wire   [14:0] datareg_41_fu_748_p3;
wire   [0:0] icmp_ln45_42_fu_760_p2;
wire   [14:0] trunc_ln42_33_fu_316_p1;
wire   [14:0] datareg_42_fu_766_p3;
wire   [0:0] icmp_ln45_43_fu_778_p2;
wire   [14:0] trunc_ln42_32_fu_312_p1;
wire   [14:0] datareg_43_fu_784_p3;
wire   [0:0] icmp_ln45_44_fu_796_p2;
wire   [14:0] trunc_ln42_31_fu_308_p1;
wire   [14:0] datareg_44_fu_802_p3;
wire   [0:0] icmp_ln45_45_fu_814_p2;
wire   [14:0] trunc_ln42_30_fu_304_p1;
wire   [14:0] datareg_45_fu_820_p3;
wire   [0:0] icmp_ln45_46_fu_832_p2;
wire   [14:0] trunc_ln42_29_fu_300_p1;
wire   [14:0] datareg_46_fu_838_p3;
wire   [0:0] icmp_ln45_47_fu_850_p2;
wire   [14:0] trunc_ln42_28_fu_296_p1;
wire   [14:0] datareg_47_fu_856_p3;
wire   [0:0] icmp_ln45_48_fu_868_p2;
wire   [14:0] trunc_ln42_27_fu_292_p1;
wire   [14:0] datareg_48_fu_874_p3;
wire   [0:0] icmp_ln45_49_fu_886_p2;
wire   [14:0] trunc_ln42_26_fu_288_p1;
wire   [14:0] datareg_49_fu_892_p3;
wire   [0:0] icmp_ln45_50_fu_904_p2;
wire   [14:0] trunc_ln42_25_fu_284_p1;
wire   [14:0] datareg_50_fu_910_p3;
wire   [0:0] icmp_ln45_51_fu_922_p2;
wire   [14:0] trunc_ln42_24_fu_280_p1;
wire   [14:0] datareg_51_fu_928_p3;
wire   [0:0] icmp_ln45_52_fu_940_p2;
wire   [14:0] trunc_ln42_23_fu_276_p1;
wire   [14:0] datareg_52_fu_946_p3;
wire   [0:0] icmp_ln45_53_fu_958_p2;
wire   [14:0] trunc_ln42_fu_272_p1;
wire   [14:0] datareg_53_fu_964_p3;
wire   [15:0] zext_ln45_fu_414_p1;
wire   [15:0] zext_ln45_23_fu_432_p1;
wire   [15:0] zext_ln45_24_fu_450_p1;
wire   [15:0] zext_ln45_25_fu_468_p1;
wire   [15:0] zext_ln45_26_fu_486_p1;
wire   [15:0] zext_ln45_27_fu_504_p1;
wire   [15:0] zext_ln45_28_fu_522_p1;
wire   [15:0] zext_ln45_29_fu_540_p1;
wire   [15:0] zext_ln45_30_fu_558_p1;
wire   [15:0] zext_ln45_31_fu_576_p1;
wire   [15:0] zext_ln45_32_fu_594_p1;
wire   [15:0] zext_ln45_33_fu_612_p1;
wire   [15:0] zext_ln45_34_fu_630_p1;
wire   [15:0] zext_ln45_35_fu_648_p1;
wire   [15:0] zext_ln45_36_fu_666_p1;
wire   [15:0] zext_ln45_37_fu_684_p1;
wire   [15:0] zext_ln45_38_fu_702_p1;
wire   [15:0] zext_ln45_39_fu_720_p1;
wire   [15:0] zext_ln45_40_fu_738_p1;
wire   [15:0] zext_ln45_41_fu_756_p1;
wire   [15:0] zext_ln45_42_fu_774_p1;
wire   [15:0] zext_ln45_43_fu_792_p1;
wire   [15:0] zext_ln45_44_fu_810_p1;
wire   [15:0] zext_ln45_45_fu_828_p1;
wire   [15:0] zext_ln45_46_fu_846_p1;
wire   [15:0] zext_ln45_47_fu_864_p1;
wire   [15:0] zext_ln45_48_fu_882_p1;
wire   [15:0] zext_ln45_49_fu_900_p1;
wire   [15:0] zext_ln45_50_fu_918_p1;
wire   [15:0] zext_ln45_51_fu_936_p1;
wire   [15:0] zext_ln45_52_fu_954_p1;
wire   [15:0] zext_ln45_53_fu_972_p1;

assign ap_ready = 1'b1;

assign datareg_23_fu_424_p3 = ((icmp_ln45_23_fu_418_p2[0:0] == 1'b1) ? trunc_ln42_52_fu_392_p1 : 15'd0);

assign datareg_24_fu_442_p3 = ((icmp_ln45_24_fu_436_p2[0:0] == 1'b1) ? trunc_ln42_51_fu_388_p1 : 15'd0);

assign datareg_25_fu_460_p3 = ((icmp_ln45_25_fu_454_p2[0:0] == 1'b1) ? trunc_ln42_50_fu_384_p1 : 15'd0);

assign datareg_26_fu_478_p3 = ((icmp_ln45_26_fu_472_p2[0:0] == 1'b1) ? trunc_ln42_49_fu_380_p1 : 15'd0);

assign datareg_27_fu_496_p3 = ((icmp_ln45_27_fu_490_p2[0:0] == 1'b1) ? trunc_ln42_48_fu_376_p1 : 15'd0);

assign datareg_28_fu_514_p3 = ((icmp_ln45_28_fu_508_p2[0:0] == 1'b1) ? trunc_ln42_47_fu_372_p1 : 15'd0);

assign datareg_29_fu_532_p3 = ((icmp_ln45_29_fu_526_p2[0:0] == 1'b1) ? trunc_ln42_46_fu_368_p1 : 15'd0);

assign datareg_30_fu_550_p3 = ((icmp_ln45_30_fu_544_p2[0:0] == 1'b1) ? trunc_ln42_45_fu_364_p1 : 15'd0);

assign datareg_31_fu_568_p3 = ((icmp_ln45_31_fu_562_p2[0:0] == 1'b1) ? trunc_ln42_44_fu_360_p1 : 15'd0);

assign datareg_32_fu_586_p3 = ((icmp_ln45_32_fu_580_p2[0:0] == 1'b1) ? trunc_ln42_43_fu_356_p1 : 15'd0);

assign datareg_33_fu_604_p3 = ((icmp_ln45_33_fu_598_p2[0:0] == 1'b1) ? trunc_ln42_42_fu_352_p1 : 15'd0);

assign datareg_34_fu_622_p3 = ((icmp_ln45_34_fu_616_p2[0:0] == 1'b1) ? trunc_ln42_41_fu_348_p1 : 15'd0);

assign datareg_35_fu_640_p3 = ((icmp_ln45_35_fu_634_p2[0:0] == 1'b1) ? trunc_ln42_40_fu_344_p1 : 15'd0);

assign datareg_36_fu_658_p3 = ((icmp_ln45_36_fu_652_p2[0:0] == 1'b1) ? trunc_ln42_39_fu_340_p1 : 15'd0);

assign datareg_37_fu_676_p3 = ((icmp_ln45_37_fu_670_p2[0:0] == 1'b1) ? trunc_ln42_38_fu_336_p1 : 15'd0);

assign datareg_38_fu_694_p3 = ((icmp_ln45_38_fu_688_p2[0:0] == 1'b1) ? trunc_ln42_37_fu_332_p1 : 15'd0);

assign datareg_39_fu_712_p3 = ((icmp_ln45_39_fu_706_p2[0:0] == 1'b1) ? trunc_ln42_36_fu_328_p1 : 15'd0);

assign datareg_40_fu_730_p3 = ((icmp_ln45_40_fu_724_p2[0:0] == 1'b1) ? trunc_ln42_35_fu_324_p1 : 15'd0);

assign datareg_41_fu_748_p3 = ((icmp_ln45_41_fu_742_p2[0:0] == 1'b1) ? trunc_ln42_34_fu_320_p1 : 15'd0);

assign datareg_42_fu_766_p3 = ((icmp_ln45_42_fu_760_p2[0:0] == 1'b1) ? trunc_ln42_33_fu_316_p1 : 15'd0);

assign datareg_43_fu_784_p3 = ((icmp_ln45_43_fu_778_p2[0:0] == 1'b1) ? trunc_ln42_32_fu_312_p1 : 15'd0);

assign datareg_44_fu_802_p3 = ((icmp_ln45_44_fu_796_p2[0:0] == 1'b1) ? trunc_ln42_31_fu_308_p1 : 15'd0);

assign datareg_45_fu_820_p3 = ((icmp_ln45_45_fu_814_p2[0:0] == 1'b1) ? trunc_ln42_30_fu_304_p1 : 15'd0);

assign datareg_46_fu_838_p3 = ((icmp_ln45_46_fu_832_p2[0:0] == 1'b1) ? trunc_ln42_29_fu_300_p1 : 15'd0);

assign datareg_47_fu_856_p3 = ((icmp_ln45_47_fu_850_p2[0:0] == 1'b1) ? trunc_ln42_28_fu_296_p1 : 15'd0);

assign datareg_48_fu_874_p3 = ((icmp_ln45_48_fu_868_p2[0:0] == 1'b1) ? trunc_ln42_27_fu_292_p1 : 15'd0);

assign datareg_49_fu_892_p3 = ((icmp_ln45_49_fu_886_p2[0:0] == 1'b1) ? trunc_ln42_26_fu_288_p1 : 15'd0);

assign datareg_50_fu_910_p3 = ((icmp_ln45_50_fu_904_p2[0:0] == 1'b1) ? trunc_ln42_25_fu_284_p1 : 15'd0);

assign datareg_51_fu_928_p3 = ((icmp_ln45_51_fu_922_p2[0:0] == 1'b1) ? trunc_ln42_24_fu_280_p1 : 15'd0);

assign datareg_52_fu_946_p3 = ((icmp_ln45_52_fu_940_p2[0:0] == 1'b1) ? trunc_ln42_23_fu_276_p1 : 15'd0);

assign datareg_53_fu_964_p3 = ((icmp_ln45_53_fu_958_p2[0:0] == 1'b1) ? trunc_ln42_fu_272_p1 : 15'd0);

assign datareg_fu_406_p3 = ((icmp_ln45_fu_400_p2[0:0] == 1'b1) ? trunc_ln42_53_fu_396_p1 : 15'd0);

assign trunc_ln42_23_fu_276_p1 = data_30_val[14:0];

assign trunc_ln42_24_fu_280_p1 = data_29_val[14:0];

assign trunc_ln42_25_fu_284_p1 = data_28_val[14:0];

assign trunc_ln42_26_fu_288_p1 = data_27_val[14:0];

assign trunc_ln42_27_fu_292_p1 = data_26_val[14:0];

assign trunc_ln42_28_fu_296_p1 = data_25_val[14:0];

assign trunc_ln42_29_fu_300_p1 = data_24_val[14:0];

assign trunc_ln42_30_fu_304_p1 = data_23_val[14:0];

assign trunc_ln42_31_fu_308_p1 = data_22_val[14:0];

assign trunc_ln42_32_fu_312_p1 = data_21_val[14:0];

assign trunc_ln42_33_fu_316_p1 = data_20_val[14:0];

assign trunc_ln42_34_fu_320_p1 = data_19_val[14:0];

assign trunc_ln42_35_fu_324_p1 = data_18_val[14:0];

assign trunc_ln42_36_fu_328_p1 = data_17_val[14:0];

assign trunc_ln42_37_fu_332_p1 = data_16_val[14:0];

assign trunc_ln42_38_fu_336_p1 = data_15_val[14:0];

assign trunc_ln42_39_fu_340_p1 = data_14_val[14:0];

assign trunc_ln42_40_fu_344_p1 = data_13_val[14:0];

assign trunc_ln42_41_fu_348_p1 = data_12_val[14:0];

assign trunc_ln42_42_fu_352_p1 = data_11_val[14:0];

assign trunc_ln42_43_fu_356_p1 = data_10_val[14:0];

assign trunc_ln42_44_fu_360_p1 = data_9_val[14:0];

assign trunc_ln42_45_fu_364_p1 = data_8_val[14:0];

assign trunc_ln42_46_fu_368_p1 = data_7_val[14:0];

assign trunc_ln42_47_fu_372_p1 = data_6_val[14:0];

assign trunc_ln42_48_fu_376_p1 = data_5_val[14:0];

assign trunc_ln42_49_fu_380_p1 = data_4_val[14:0];

assign trunc_ln42_50_fu_384_p1 = data_3_val[14:0];

assign trunc_ln42_51_fu_388_p1 = data_2_val[14:0];

assign trunc_ln42_52_fu_392_p1 = data_1_val[14:0];

assign trunc_ln42_53_fu_396_p1 = data_0_val[14:0];

assign trunc_ln42_fu_272_p1 = data_31_val[14:0];

assign zext_ln45_23_fu_432_p1 = datareg_23_fu_424_p3;

assign zext_ln45_24_fu_450_p1 = datareg_24_fu_442_p3;

assign zext_ln45_25_fu_468_p1 = datareg_25_fu_460_p3;

assign zext_ln45_26_fu_486_p1 = datareg_26_fu_478_p3;

assign zext_ln45_27_fu_504_p1 = datareg_27_fu_496_p3;

assign zext_ln45_28_fu_522_p1 = datareg_28_fu_514_p3;

assign zext_ln45_29_fu_540_p1 = datareg_29_fu_532_p3;

assign zext_ln45_30_fu_558_p1 = datareg_30_fu_550_p3;

assign zext_ln45_31_fu_576_p1 = datareg_31_fu_568_p3;

assign zext_ln45_32_fu_594_p1 = datareg_32_fu_586_p3;

assign zext_ln45_33_fu_612_p1 = datareg_33_fu_604_p3;

assign zext_ln45_34_fu_630_p1 = datareg_34_fu_622_p3;

assign zext_ln45_35_fu_648_p1 = datareg_35_fu_640_p3;

assign zext_ln45_36_fu_666_p1 = datareg_36_fu_658_p3;

assign zext_ln45_37_fu_684_p1 = datareg_37_fu_676_p3;

assign zext_ln45_38_fu_702_p1 = datareg_38_fu_694_p3;

assign zext_ln45_39_fu_720_p1 = datareg_39_fu_712_p3;

assign zext_ln45_40_fu_738_p1 = datareg_40_fu_730_p3;

assign zext_ln45_41_fu_756_p1 = datareg_41_fu_748_p3;

assign zext_ln45_42_fu_774_p1 = datareg_42_fu_766_p3;

assign zext_ln45_43_fu_792_p1 = datareg_43_fu_784_p3;

assign zext_ln45_44_fu_810_p1 = datareg_44_fu_802_p3;

assign zext_ln45_45_fu_828_p1 = datareg_45_fu_820_p3;

assign zext_ln45_46_fu_846_p1 = datareg_46_fu_838_p3;

assign zext_ln45_47_fu_864_p1 = datareg_47_fu_856_p3;

assign zext_ln45_48_fu_882_p1 = datareg_48_fu_874_p3;

assign zext_ln45_49_fu_900_p1 = datareg_49_fu_892_p3;

assign zext_ln45_50_fu_918_p1 = datareg_50_fu_910_p3;

assign zext_ln45_51_fu_936_p1 = datareg_51_fu_928_p3;

assign zext_ln45_52_fu_954_p1 = datareg_52_fu_946_p3;

assign zext_ln45_53_fu_972_p1 = datareg_53_fu_964_p3;

assign zext_ln45_fu_414_p1 = datareg_fu_406_p3;

assign ap_return_0 = zext_ln45_fu_414_p1;

assign ap_return_1 = zext_ln45_23_fu_432_p1;

assign ap_return_10 = zext_ln45_32_fu_594_p1;

assign ap_return_11 = zext_ln45_33_fu_612_p1;

assign ap_return_12 = zext_ln45_34_fu_630_p1;

assign ap_return_13 = zext_ln45_35_fu_648_p1;

assign ap_return_14 = zext_ln45_36_fu_666_p1;

assign ap_return_15 = zext_ln45_37_fu_684_p1;

assign ap_return_16 = zext_ln45_38_fu_702_p1;

assign ap_return_17 = zext_ln45_39_fu_720_p1;

assign ap_return_18 = zext_ln45_40_fu_738_p1;

assign ap_return_19 = zext_ln45_41_fu_756_p1;

assign ap_return_2 = zext_ln45_24_fu_450_p1;

assign ap_return_20 = zext_ln45_42_fu_774_p1;

assign ap_return_21 = zext_ln45_43_fu_792_p1;

assign ap_return_22 = zext_ln45_44_fu_810_p1;

assign ap_return_23 = zext_ln45_45_fu_828_p1;

assign ap_return_24 = zext_ln45_46_fu_846_p1;

assign ap_return_25 = zext_ln45_47_fu_864_p1;

assign ap_return_26 = zext_ln45_48_fu_882_p1;

assign ap_return_27 = zext_ln45_49_fu_900_p1;

assign ap_return_28 = zext_ln45_50_fu_918_p1;

assign ap_return_29 = zext_ln45_51_fu_936_p1;

assign ap_return_3 = zext_ln45_25_fu_468_p1;

assign ap_return_30 = zext_ln45_52_fu_954_p1;

assign ap_return_31 = zext_ln45_53_fu_972_p1;

assign ap_return_4 = zext_ln45_26_fu_486_p1;

assign ap_return_5 = zext_ln45_27_fu_504_p1;

assign ap_return_6 = zext_ln45_28_fu_522_p1;

assign ap_return_7 = zext_ln45_29_fu_540_p1;

assign ap_return_8 = zext_ln45_30_fu_558_p1;

assign ap_return_9 = zext_ln45_31_fu_576_p1;

assign icmp_ln45_23_fu_418_p2 = (($signed(data_1_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_24_fu_436_p2 = (($signed(data_2_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_25_fu_454_p2 = (($signed(data_3_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_26_fu_472_p2 = (($signed(data_4_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_27_fu_490_p2 = (($signed(data_5_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_28_fu_508_p2 = (($signed(data_6_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_29_fu_526_p2 = (($signed(data_7_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_30_fu_544_p2 = (($signed(data_8_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_31_fu_562_p2 = (($signed(data_9_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_32_fu_580_p2 = (($signed(data_10_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_33_fu_598_p2 = (($signed(data_11_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_34_fu_616_p2 = (($signed(data_12_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_35_fu_634_p2 = (($signed(data_13_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_36_fu_652_p2 = (($signed(data_14_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_37_fu_670_p2 = (($signed(data_15_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_38_fu_688_p2 = (($signed(data_16_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_39_fu_706_p2 = (($signed(data_17_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_40_fu_724_p2 = (($signed(data_18_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_41_fu_742_p2 = (($signed(data_19_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_42_fu_760_p2 = (($signed(data_20_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_43_fu_778_p2 = (($signed(data_21_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_44_fu_796_p2 = (($signed(data_22_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_45_fu_814_p2 = (($signed(data_23_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_46_fu_832_p2 = (($signed(data_24_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_47_fu_850_p2 = (($signed(data_25_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_48_fu_868_p2 = (($signed(data_26_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_49_fu_886_p2 = (($signed(data_27_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_50_fu_904_p2 = (($signed(data_28_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_51_fu_922_p2 = (($signed(data_29_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_52_fu_940_p2 = (($signed(data_30_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_53_fu_958_p2 = (($signed(data_31_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_400_p2 = (($signed(data_0_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

endmodule //myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s
