-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config9_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config9_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv10_1FF : STD_LOGIC_VECTOR (9 downto 0) := "0111111111";
    constant ap_const_lv10_200 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv9_1FF : STD_LOGIC_VECTOR (8 downto 0) := "111111111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal exp_table_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_ce0 : STD_LOGIC;
    signal exp_table_q0 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_table_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_ce1 : STD_LOGIC;
    signal exp_table_q1 : STD_LOGIC_VECTOR (16 downto 0);
    signal invert_table_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal invert_table_ce0 : STD_LOGIC;
    signal invert_table_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal exp_table_load_reg_393 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_table_load_1_reg_398 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln255_fu_242_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln255_1_fu_273_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln265_fu_324_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln66_fu_104_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln66_fu_104_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln66_fu_104_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_fu_110_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_max_fu_116_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_max_fu_116_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln245_fu_124_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_max_fu_116_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln245_fu_124_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln245_1_fu_128_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln245_fu_132_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_2_fu_138_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_146_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln245_fu_154_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln245_2_fu_172_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln245_2_fu_172_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln245_1_fu_176_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_4_fu_182_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_190_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln245_2_fu_198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln245_fu_160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln245_1_fu_166_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln245_fu_216_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_fu_224_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln245_1_fu_234_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln245_1_fu_204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln245_3_fu_210_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln245_2_fu_247_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_1_fu_255_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln245_3_fu_265_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_fu_282_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln245_fu_278_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln51_fu_292_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln51_1_fu_286_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_6_fu_298_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_cast_fu_306_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln51_fu_316_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln268_fu_336_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln268_fu_329_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln268_fu_336_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln268_fu_336_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln268_1_fu_355_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln268_1_fu_355_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln268_1_fu_355_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal mul_ln268_1_fu_355_p10 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln268_fu_336_p10 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component myproject_mul_18s_17ns_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (16 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config9_s_exp_table_ROM_Abkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config9_s_invert_table_ROcud IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;



begin
    exp_table_U : component myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config9_s_exp_table_ROM_Abkb
    generic map (
        DataWidth => 17,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => exp_table_address0,
        ce0 => exp_table_ce0,
        q0 => exp_table_q0,
        address1 => exp_table_address1,
        ce1 => exp_table_ce1,
        q1 => exp_table_q1);

    invert_table_U : component myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config9_s_invert_table_ROcud
    generic map (
        DataWidth => 18,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => invert_table_address0,
        ce0 => invert_table_ce0,
        q0 => invert_table_q0);

    mul_18s_17ns_26_1_1_U419 : component myproject_mul_18s_17ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 17,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln268_fu_336_p0,
        din1 => mul_ln268_fu_336_p1,
        dout => mul_ln268_fu_336_p2);

    mul_18s_17ns_26_1_1_U420 : component myproject_mul_18s_17ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 17,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln268_1_fu_355_p0,
        din1 => mul_ln268_1_fu_355_p1,
        dout => mul_ln268_1_fu_355_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                exp_table_load_1_reg_398 <= exp_table_q0;
                exp_table_load_reg_393 <= exp_table_q1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln51_1_fu_286_p2 <= std_logic_vector(unsigned(exp_table_q0) + unsigned(exp_table_q1));
    add_ln51_fu_292_p2 <= std_logic_vector(unsigned(zext_ln51_fu_282_p1) + unsigned(zext_ln245_fu_278_p1));
    and_ln245_1_fu_204_p2 <= (xor_ln245_2_fu_198_p2 and tmp_5_fu_190_p3);
    and_ln245_fu_160_p2 <= (xor_ln245_fu_154_p2 and tmp_3_fu_146_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= (ap_const_logic_0 = ap_ce);
    end process;


    ap_done_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to1 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= mul_ln268_fu_336_p2(25 downto 10);
    ap_return_1 <= mul_ln268_1_fu_355_p2(25 downto 10);
    exp_table_address0 <= zext_ln255_1_fu_273_p1(10 - 1 downto 0);
    exp_table_address1 <= zext_ln255_fu_242_p1(10 - 1 downto 0);

    exp_table_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table_ce0 <= ap_const_logic_1;
        else 
            exp_table_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table_ce1 <= ap_const_logic_1;
        else 
            exp_table_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln66_fu_104_p0 <= data_0_val;
    icmp_ln66_fu_104_p1 <= data_1_val;
    icmp_ln66_fu_104_p2 <= "1" when (signed(icmp_ln66_fu_104_p0) < signed(icmp_ln66_fu_104_p1)) else "0";
    invert_table_address0 <= zext_ln265_fu_324_p1(10 - 1 downto 0);

    invert_table_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            invert_table_ce0 <= ap_const_logic_1;
        else 
            invert_table_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln268_1_fu_355_p0 <= sext_ln268_fu_329_p1(18 - 1 downto 0);
    mul_ln268_1_fu_355_p1 <= mul_ln268_1_fu_355_p10(17 - 1 downto 0);
    mul_ln268_1_fu_355_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_1_reg_398),26));
    mul_ln268_fu_336_p0 <= sext_ln268_fu_329_p1(18 - 1 downto 0);
    mul_ln268_fu_336_p1 <= mul_ln268_fu_336_p10(17 - 1 downto 0);
    mul_ln268_fu_336_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_load_reg_393),26));
    select_ln245_1_fu_234_p3 <= 
        select_ln245_fu_216_p3 when (xor_ln245_1_fu_166_p2(0) = '1') else 
        tmp_fu_224_p4;
    select_ln245_2_fu_247_p3 <= 
        ap_const_lv10_1FF when (and_ln245_1_fu_204_p2(0) = '1') else 
        ap_const_lv10_200;
    select_ln245_3_fu_265_p3 <= 
        select_ln245_2_fu_247_p3 when (xor_ln245_3_fu_210_p2(0) = '1') else 
        tmp_1_fu_255_p4;
    select_ln245_fu_216_p3 <= 
        ap_const_lv10_1FF when (and_ln245_fu_160_p2(0) = '1') else 
        ap_const_lv10_200;
    select_ln51_fu_316_p3 <= 
        ap_const_lv9_1FF when (tmp_6_fu_298_p3(0) = '1') else 
        tmp_2_cast_fu_306_p4;
        sext_ln245_1_fu_128_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(x_max_fu_116_p3),17));

    sext_ln245_2_fu_172_p0 <= data_1_val;
        sext_ln245_2_fu_172_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln245_2_fu_172_p0),17));

    sext_ln245_fu_124_p0 <= data_0_val;
        sext_ln245_fu_124_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln245_fu_124_p0),17));

        sext_ln268_fu_329_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(invert_table_q0),26));

    sub_ln245_1_fu_176_p2 <= std_logic_vector(signed(sext_ln245_2_fu_172_p1) - signed(sext_ln245_1_fu_128_p1));
    sub_ln245_fu_132_p2 <= std_logic_vector(signed(sext_ln245_fu_124_p1) - signed(sext_ln245_1_fu_128_p1));
    tmp_1_fu_255_p4 <= sub_ln245_1_fu_176_p2(15 downto 6);
    tmp_2_cast_fu_306_p4 <= add_ln51_1_fu_286_p2(16 downto 8);
    tmp_2_fu_138_p3 <= sub_ln245_fu_132_p2(16 downto 16);
    tmp_3_fu_146_p3 <= sub_ln245_fu_132_p2(15 downto 15);
    tmp_4_fu_182_p3 <= sub_ln245_1_fu_176_p2(16 downto 16);
    tmp_5_fu_190_p3 <= sub_ln245_1_fu_176_p2(15 downto 15);
    tmp_6_fu_298_p3 <= add_ln51_fu_292_p2(17 downto 17);
    tmp_fu_224_p4 <= sub_ln245_fu_132_p2(15 downto 6);
    x_max_fu_116_p1 <= data_0_val;
    x_max_fu_116_p2 <= data_1_val;
    x_max_fu_116_p3 <= 
        x_max_fu_116_p1 when (xor_ln66_fu_110_p2(0) = '1') else 
        x_max_fu_116_p2;
    xor_ln245_1_fu_166_p2 <= (tmp_3_fu_146_p3 xor tmp_2_fu_138_p3);
    xor_ln245_2_fu_198_p2 <= (tmp_4_fu_182_p3 xor ap_const_lv1_1);
    xor_ln245_3_fu_210_p2 <= (tmp_5_fu_190_p3 xor tmp_4_fu_182_p3);
    xor_ln245_fu_154_p2 <= (tmp_2_fu_138_p3 xor ap_const_lv1_1);
    xor_ln66_fu_110_p2 <= (icmp_ln66_fu_104_p2 xor ap_const_lv1_1);
    zext_ln245_fu_278_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_q1),18));
    zext_ln255_1_fu_273_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln245_3_fu_265_p3),64));
    zext_ln255_fu_242_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln245_1_fu_234_p3),64));
    zext_ln265_fu_324_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_fu_316_p3),64));
    zext_ln51_fu_282_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_table_q0),18));
end behav;
