Backend: Vivado
ClockPeriod: 10
ClockUncertainty: 12.5%
HLSConfig:
  LayerName:
    dense_1:
      Precision:
        bias: auto
        result: auto
        weight: auto
      Trace: false
    dense_1_input:
      Precision:
        result: auto
      Trace: false
    dense_1_relu:
      Precision:
        result: auto
      Trace: false
    dense_2:
      Precision:
        bias: auto
        result: auto
        weight: auto
      Trace: false
    dense_2_softmax:
      Precision:
        result: auto
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'hls_simple_test/keras_model.keras'
OutputDir: hls_simple_test
OutputPredictions: null
Part: xcu250-figd2104-2L-e
ProjectName: myproject
Stamp: bd08c30e
Version: 1.0.0
WriterConfig:
  Namespace: null
  WriteTar: false
  WriteWeightsTxt: true
