// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        ap_return_0,
        ap_return_1,
        ap_ce
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
input  [15:0] data_5_val;
input  [15:0] data_6_val;
input  [15:0] data_7_val;
input  [15:0] data_8_val;
input  [15:0] data_9_val;
input  [15:0] data_10_val;
input  [15:0] data_11_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
input   ap_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [15:0] reg_585;
wire    ap_CS_fsm_state2;
reg   [12:0] trunc_ln42_1_reg_1009;
reg   [13:0] trunc_ln42_5_reg_1014;
wire   [15:0] add_ln58_1_fu_729_p2;
reg   [15:0] add_ln58_1_reg_1019;
wire   [15:0] add_ln58_12_fu_735_p2;
reg   [15:0] add_ln58_12_reg_1024;
wire   [15:0] grp_fu_545_p4;
reg   [15:0] trunc_ln42_10_reg_1029;
reg   [11:0] trunc_ln42_11_reg_1034;
wire  signed [25:0] sext_ln70_6_fu_822_p1;
reg  signed [25:0] sext_ln70_6_reg_1039;
reg   [15:0] trunc_ln42_13_reg_1044;
wire   [15:0] add_ln58_3_fu_843_p2;
reg   [15:0] add_ln58_3_reg_1049;
wire   [15:0] add_ln58_14_fu_855_p2;
reg   [15:0] add_ln58_14_reg_1054;
reg   [15:0] trunc_ln42_16_reg_1059;
wire    ap_CS_fsm_state3;
wire   [15:0] grp_fu_555_p4;
reg   [15:0] trunc_ln42_17_reg_1064;
reg   [10:0] trunc_ln42_18_reg_1069;
reg   [14:0] trunc_ln42_19_reg_1074;
wire   [15:0] add_ln58_5_fu_902_p2;
reg   [15:0] add_ln58_5_reg_1079;
wire   [15:0] add_ln58_16_fu_907_p2;
reg   [15:0] add_ln58_16_reg_1084;
reg   [15:0] ap_port_reg_data_4_val;
reg   [15:0] ap_port_reg_data_5_val;
reg   [15:0] ap_port_reg_data_6_val;
reg   [15:0] ap_port_reg_data_7_val;
reg   [15:0] ap_port_reg_data_8_val;
reg   [15:0] ap_port_reg_data_9_val;
reg   [15:0] ap_port_reg_data_10_val;
reg   [15:0] ap_port_reg_data_11_val;
wire    ap_CS_fsm_state4;
reg  signed [15:0] grp_fu_202_p0;
wire  signed [25:0] sext_ln42_2_fu_658_p1;
wire  signed [21:0] sext_ln70_5_fu_807_p1;
wire  signed [25:0] sext_ln70_7_fu_866_p1;
wire  signed [25:0] sext_ln73_7_fu_922_p1;
reg  signed [11:0] grp_fu_202_p1;
reg  signed [15:0] grp_fu_203_p0;
wire  signed [25:0] sext_ln73_2_fu_652_p1;
wire  signed [25:0] sext_ln70_3_fu_753_p1;
reg  signed [11:0] grp_fu_203_p1;
reg  signed [15:0] grp_fu_204_p0;
wire  signed [23:0] sext_ln70_1_fu_703_p1;
wire  signed [24:0] sext_ln70_8_fu_872_p1;
reg  signed [10:0] grp_fu_204_p1;
reg  signed [15:0] grp_fu_205_p0;
wire  signed [24:0] sext_ln70_fu_589_p1;
wire  signed [25:0] sext_ln70_2_fu_747_p1;
reg  signed [11:0] grp_fu_205_p1;
reg  signed [15:0] grp_fu_206_p0;
wire  signed [25:0] sext_ln42_8_fu_861_p1;
reg  signed [10:0] grp_fu_206_p1;
reg  signed [15:0] grp_fu_207_p0;
wire  signed [25:0] sext_ln42_4_fu_708_p1;
wire  signed [25:0] sext_ln70_4_fu_802_p1;
wire  signed [20:0] sext_ln70_9_fu_877_p1;
reg   [10:0] grp_fu_207_p1;
wire   [25:0] grp_fu_206_p2;
wire   [25:0] grp_fu_203_p2;
wire   [25:0] grp_fu_202_p2;
wire   [25:0] grp_fu_207_p2;
wire   [25:0] grp_fu_205_p2;
wire  signed [15:0] sext_ln70_fu_589_p0;
wire   [24:0] trunc_ln_fu_594_p1;
wire   [14:0] trunc_ln_fu_594_p4;
wire  signed [15:0] shl_ln_fu_608_p1;
wire   [23:0] shl_ln_fu_608_p3;
wire  signed [15:0] shl_ln73_1_fu_620_p1;
wire   [18:0] shl_ln73_1_fu_620_p3;
wire  signed [24:0] sext_ln73_fu_616_p1;
wire  signed [24:0] sext_ln73_1_fu_628_p1;
wire   [24:0] add_ln73_fu_632_p2;
wire   [14:0] trunc_ln42_s_fu_638_p4;
wire  signed [15:0] sext_ln42_2_fu_658_p0;
wire  signed [15:0] shl_ln73_2_fu_663_p1;
wire   [21:0] shl_ln73_2_fu_663_p3;
wire  signed [15:0] shl_ln73_3_fu_675_p1;
wire   [16:0] shl_ln73_3_fu_675_p3;
wire  signed [22:0] sext_ln73_3_fu_671_p1;
wire  signed [22:0] sext_ln73_4_fu_683_p1;
wire   [22:0] add_ln73_1_fu_687_p2;
wire  signed [15:0] sext_ln70_1_fu_703_p0;
wire  signed [15:0] sext_ln42_4_fu_708_p0;
wire   [23:0] trunc_ln42_5_fu_713_p1;
wire   [25:0] grp_fu_204_p2;
wire   [15:0] grp_fu_535_p4;
wire   [15:0] add_ln58_fu_723_p2;
wire  signed [15:0] sext_ln42_fu_604_p1;
wire  signed [15:0] sext_ln42_1_fu_648_p1;
wire  signed [15:0] sext_ln70_3_fu_753_p0;
wire  signed [15:0] shl_ln73_4_fu_758_p1;
wire   [21:0] shl_ln73_4_fu_758_p3;
wire  signed [15:0] shl_ln73_5_fu_770_p1;
wire   [17:0] shl_ln73_5_fu_770_p3;
wire  signed [22:0] sext_ln73_5_fu_766_p1;
wire  signed [22:0] sext_ln73_6_fu_778_p1;
wire   [22:0] add_ln73_2_fu_782_p2;
wire   [12:0] trunc_ln42_7_fu_788_p4;
wire  signed [15:0] sext_ln70_4_fu_802_p0;
wire  signed [15:0] sext_ln70_5_fu_807_p0;
wire   [21:0] trunc_ln42_11_fu_812_p1;
wire   [15:0] grp_fu_575_p4;
wire  signed [15:0] sext_ln42_6_fu_798_p1;
wire   [15:0] add_ln58_2_fu_837_p2;
wire  signed [15:0] sext_ln42_5_fu_744_p1;
wire   [15:0] add_ln58_13_fu_849_p2;
wire  signed [15:0] sext_ln42_3_fu_741_p1;
wire  signed [15:0] sext_ln70_8_fu_872_p0;
wire  signed [15:0] sext_ln70_9_fu_877_p0;
wire   [20:0] trunc_ln42_18_fu_882_p1;
wire   [24:0] trunc_ln42_19_fu_892_p1;
wire  signed [15:0] sext_ln42_7_fu_913_p1;
wire  signed [15:0] sext_ln42_9_fu_916_p1;
wire   [15:0] add_ln58_8_fu_942_p2;
wire   [15:0] add_ln58_7_fu_937_p2;
wire   [15:0] add_ln58_9_fu_948_p2;
wire   [15:0] add_ln58_6_fu_932_p2;
wire   [15:0] add_ln58_10_fu_954_p2;
wire   [15:0] add_ln58_4_fu_928_p2;
wire  signed [15:0] sext_ln42_10_fu_919_p1;
wire   [15:0] add_ln58_18_fu_974_p2;
wire   [15:0] add_ln58_19_fu_980_p2;
wire   [15:0] add_ln58_17_fu_970_p2;
wire   [15:0] add_ln58_20_fu_985_p2;
wire   [15:0] add_ln58_15_fu_966_p2;
wire   [15:0] add_ln58_11_fu_960_p2;
wire   [15:0] add_ln58_21_fu_991_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
end

myproject_mul_16s_12s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_1_1_U238(
    .din0(grp_fu_202_p0),
    .din1(grp_fu_202_p1),
    .dout(grp_fu_202_p2)
);

myproject_mul_16s_12s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_1_1_U239(
    .din0(grp_fu_203_p0),
    .din1(grp_fu_203_p1),
    .dout(grp_fu_203_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U240(
    .din0(grp_fu_204_p0),
    .din1(grp_fu_204_p1),
    .dout(grp_fu_204_p2)
);

myproject_mul_16s_12s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_1_1_U241(
    .din0(grp_fu_205_p0),
    .din1(grp_fu_205_p1),
    .dout(grp_fu_205_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U242(
    .din0(grp_fu_206_p0),
    .din1(grp_fu_206_p1),
    .dout(grp_fu_206_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U243(
    .din0(grp_fu_207_p0),
    .din1(grp_fu_207_p1),
    .dout(grp_fu_207_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add_ln58_12_reg_1024 <= add_ln58_12_fu_735_p2;
        add_ln58_1_reg_1019 <= add_ln58_1_fu_729_p2;
        trunc_ln42_1_reg_1009 <= {{add_ln73_1_fu_687_p2[22:10]}};
        trunc_ln42_5_reg_1014 <= {{trunc_ln42_5_fu_713_p1[23:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln58_14_reg_1054 <= add_ln58_14_fu_855_p2;
        add_ln58_3_reg_1049 <= add_ln58_3_fu_843_p2;
        sext_ln70_6_reg_1039 <= sext_ln70_6_fu_822_p1;
        trunc_ln42_10_reg_1029 <= {{grp_fu_203_p2[25:10]}};
        trunc_ln42_11_reg_1034 <= {{trunc_ln42_11_fu_812_p1[21:10]}};
        trunc_ln42_13_reg_1044 <= {{grp_fu_204_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln58_16_reg_1084 <= add_ln58_16_fu_907_p2;
        add_ln58_5_reg_1079 <= add_ln58_5_fu_902_p2;
        trunc_ln42_16_reg_1059 <= {{grp_fu_203_p2[25:10]}};
        trunc_ln42_17_reg_1064 <= {{grp_fu_202_p2[25:10]}};
        trunc_ln42_18_reg_1069 <= {{trunc_ln42_18_fu_882_p1[20:10]}};
        trunc_ln42_19_reg_1074 <= {{trunc_ln42_19_fu_892_p1[24:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_port_reg_data_10_val <= data_10_val;
        ap_port_reg_data_11_val <= data_11_val;
        ap_port_reg_data_4_val <= data_4_val;
        ap_port_reg_data_5_val <= data_5_val;
        ap_port_reg_data_6_val <= data_6_val;
        ap_port_reg_data_7_val <= data_7_val;
        ap_port_reg_data_8_val <= data_8_val;
        ap_port_reg_data_9_val <= data_9_val;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (1'b1 == ap_ce)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        reg_585 <= {{grp_fu_207_p2[25:10]}};
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (1'b0 == ap_ce))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state4)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_202_p0 = sext_ln73_7_fu_922_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_202_p0 = sext_ln70_7_fu_866_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_202_p0 = sext_ln70_5_fu_807_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_202_p0 = sext_ln42_2_fu_658_p1;
    end else begin
        grp_fu_202_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_202_p1 = 26'd534;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_202_p1 = 26'd67108540;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_202_p1 = 22'd4194283;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_202_p1 = 26'd67108229;
    end else begin
        grp_fu_202_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_203_p0 = sext_ln70_7_fu_866_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_203_p0 = sext_ln70_3_fu_753_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_203_p0 = sext_ln73_2_fu_652_p1;
    end else begin
        grp_fu_203_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_203_p1 = 26'd67108530;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_203_p1 = 26'd67108557;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_203_p1 = 26'd551;
    end else begin
        grp_fu_203_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_204_p0 = sext_ln70_8_fu_872_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_204_p0 = sext_ln70_6_fu_822_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_204_p0 = sext_ln70_1_fu_703_p1;
    end else begin
        grp_fu_204_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_204_p1 = 25'd33554277;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_204_p1 = 26'd394;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_204_p1 = 24'd108;
    end else begin
        grp_fu_204_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_205_p0 = sext_ln73_7_fu_922_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_205_p0 = sext_ln70_6_reg_1039;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_205_p0 = sext_ln70_2_fu_747_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_205_p0 = sext_ln70_fu_589_p1;
    end else begin
        grp_fu_205_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_205_p1 = 26'd566;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_205_p1 = 26'd67108505;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_205_p1 = 26'd517;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_205_p1 = 25'd33554281;
    end else begin
        grp_fu_205_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_206_p0 = sext_ln42_8_fu_861_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_206_p0 = sext_ln70_2_fu_747_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_206_p0 = sext_ln73_2_fu_652_p1;
    end else begin
        grp_fu_206_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_206_p1 = 26'd67108343;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_206_p1 = 26'd67108495;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_206_p1 = 26'd67108305;
    end else begin
        grp_fu_206_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_207_p0 = sext_ln70_9_fu_877_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_207_p0 = sext_ln70_4_fu_802_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_207_p0 = sext_ln42_4_fu_708_p1;
    end else begin
        grp_fu_207_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_207_p1 = 21'd11;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_207_p1 = 26'd382;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_207_p1 = 26'd580;
    end else begin
        grp_fu_207_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b1 == ap_ce))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (1'b1 == ap_ce))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_10_fu_954_p2 = (add_ln58_9_fu_948_p2 + add_ln58_6_fu_932_p2);

assign add_ln58_11_fu_960_p2 = (add_ln58_10_fu_954_p2 + add_ln58_4_fu_928_p2);

assign add_ln58_12_fu_735_p2 = ($signed(grp_fu_545_p4) + $signed(sext_ln42_1_fu_648_p1));

assign add_ln58_13_fu_849_p2 = ($signed(sext_ln42_5_fu_744_p1) + $signed(grp_fu_535_p4));

assign add_ln58_14_fu_855_p2 = ($signed(add_ln58_13_fu_849_p2) + $signed(sext_ln42_3_fu_741_p1));

assign add_ln58_15_fu_966_p2 = (add_ln58_14_reg_1054 + add_ln58_12_reg_1024);

assign add_ln58_16_fu_907_p2 = (reg_585 + grp_fu_575_p4);

assign add_ln58_17_fu_970_p2 = (add_ln58_16_reg_1084 + trunc_ln42_10_reg_1029);

assign add_ln58_18_fu_974_p2 = ($signed(sext_ln42_10_fu_919_p1) + $signed(grp_fu_555_p4));

assign add_ln58_19_fu_980_p2 = (add_ln58_18_fu_974_p2 + trunc_ln42_17_reg_1064);

assign add_ln58_1_fu_729_p2 = ($signed(add_ln58_fu_723_p2) + $signed(sext_ln42_fu_604_p1));

assign add_ln58_20_fu_985_p2 = (add_ln58_19_fu_980_p2 + add_ln58_17_fu_970_p2);

assign add_ln58_21_fu_991_p2 = (add_ln58_20_fu_985_p2 + add_ln58_15_fu_966_p2);

assign add_ln58_2_fu_837_p2 = ($signed(grp_fu_575_p4) + $signed(sext_ln42_6_fu_798_p1));

assign add_ln58_3_fu_843_p2 = (add_ln58_2_fu_837_p2 + reg_585);

assign add_ln58_4_fu_928_p2 = (add_ln58_3_reg_1049 + add_ln58_1_reg_1019);

assign add_ln58_5_fu_902_p2 = (trunc_ln42_13_reg_1044 + grp_fu_535_p4);

assign add_ln58_6_fu_932_p2 = ($signed(add_ln58_5_reg_1079) + $signed(sext_ln42_7_fu_913_p1));

assign add_ln58_7_fu_937_p2 = ($signed(trunc_ln42_16_reg_1059) + $signed(sext_ln42_9_fu_916_p1));

assign add_ln58_8_fu_942_p2 = ($signed(grp_fu_575_p4) + $signed(16'd65535));

assign add_ln58_9_fu_948_p2 = (add_ln58_8_fu_942_p2 + add_ln58_7_fu_937_p2);

assign add_ln58_fu_723_p2 = (grp_fu_535_p4 + grp_fu_555_p4);

assign add_ln73_1_fu_687_p2 = ($signed(sext_ln73_3_fu_671_p1) + $signed(sext_ln73_4_fu_683_p1));

assign add_ln73_2_fu_782_p2 = ($signed(sext_ln73_5_fu_766_p1) + $signed(sext_ln73_6_fu_778_p1));

assign add_ln73_fu_632_p2 = ($signed(sext_ln73_fu_616_p1) + $signed(sext_ln73_1_fu_628_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_return_0 = add_ln58_11_fu_960_p2;

assign ap_return_1 = add_ln58_21_fu_991_p2;

assign grp_fu_535_p4 = {{grp_fu_206_p2[25:10]}};

assign grp_fu_545_p4 = {{grp_fu_203_p2[25:10]}};

assign grp_fu_555_p4 = {{grp_fu_202_p2[25:10]}};

assign grp_fu_575_p4 = {{grp_fu_205_p2[25:10]}};

assign sext_ln42_10_fu_919_p1 = $signed(trunc_ln42_19_reg_1074);

assign sext_ln42_1_fu_648_p1 = $signed(trunc_ln42_s_fu_638_p4);

assign sext_ln42_2_fu_658_p0 = data_2_val;

assign sext_ln42_2_fu_658_p1 = sext_ln42_2_fu_658_p0;

assign sext_ln42_3_fu_741_p1 = $signed(trunc_ln42_1_reg_1009);

assign sext_ln42_4_fu_708_p0 = data_3_val;

assign sext_ln42_4_fu_708_p1 = sext_ln42_4_fu_708_p0;

assign sext_ln42_5_fu_744_p1 = $signed(trunc_ln42_5_reg_1014);

assign sext_ln42_6_fu_798_p1 = $signed(trunc_ln42_7_fu_788_p4);

assign sext_ln42_7_fu_913_p1 = $signed(trunc_ln42_11_reg_1034);

assign sext_ln42_8_fu_861_p1 = $signed(ap_port_reg_data_8_val);

assign sext_ln42_9_fu_916_p1 = $signed(trunc_ln42_18_reg_1069);

assign sext_ln42_fu_604_p1 = $signed(trunc_ln_fu_594_p4);

assign sext_ln70_1_fu_703_p0 = data_3_val;

assign sext_ln70_1_fu_703_p1 = sext_ln70_1_fu_703_p0;

assign sext_ln70_2_fu_747_p1 = $signed(ap_port_reg_data_4_val);

assign sext_ln70_3_fu_753_p0 = ap_port_reg_data_5_val;

assign sext_ln70_3_fu_753_p1 = sext_ln70_3_fu_753_p0;

assign sext_ln70_4_fu_802_p0 = ap_port_reg_data_6_val;

assign sext_ln70_4_fu_802_p1 = sext_ln70_4_fu_802_p0;

assign sext_ln70_5_fu_807_p0 = ap_port_reg_data_6_val;

assign sext_ln70_5_fu_807_p1 = sext_ln70_5_fu_807_p0;

assign sext_ln70_6_fu_822_p1 = $signed(ap_port_reg_data_7_val);

assign sext_ln70_7_fu_866_p1 = $signed(ap_port_reg_data_9_val);

assign sext_ln70_8_fu_872_p0 = ap_port_reg_data_10_val;

assign sext_ln70_8_fu_872_p1 = sext_ln70_8_fu_872_p0;

assign sext_ln70_9_fu_877_p0 = ap_port_reg_data_10_val;

assign sext_ln70_9_fu_877_p1 = sext_ln70_9_fu_877_p0;

assign sext_ln70_fu_589_p0 = data_0_val;

assign sext_ln70_fu_589_p1 = sext_ln70_fu_589_p0;

assign sext_ln73_1_fu_628_p1 = $signed(shl_ln73_1_fu_620_p3);

assign sext_ln73_2_fu_652_p1 = $signed(data_1_val);

assign sext_ln73_3_fu_671_p1 = $signed(shl_ln73_2_fu_663_p3);

assign sext_ln73_4_fu_683_p1 = $signed(shl_ln73_3_fu_675_p3);

assign sext_ln73_5_fu_766_p1 = $signed(shl_ln73_4_fu_758_p3);

assign sext_ln73_6_fu_778_p1 = $signed(shl_ln73_5_fu_770_p3);

assign sext_ln73_7_fu_922_p1 = $signed(ap_port_reg_data_11_val);

assign sext_ln73_fu_616_p1 = $signed(shl_ln_fu_608_p3);

assign shl_ln73_1_fu_620_p1 = data_0_val;

assign shl_ln73_1_fu_620_p3 = {{shl_ln73_1_fu_620_p1}, {3'd0}};

assign shl_ln73_2_fu_663_p1 = data_2_val;

assign shl_ln73_2_fu_663_p3 = {{shl_ln73_2_fu_663_p1}, {6'd0}};

assign shl_ln73_3_fu_675_p1 = data_2_val;

assign shl_ln73_3_fu_675_p3 = {{shl_ln73_3_fu_675_p1}, {1'd0}};

assign shl_ln73_4_fu_758_p1 = ap_port_reg_data_5_val;

assign shl_ln73_4_fu_758_p3 = {{shl_ln73_4_fu_758_p1}, {6'd0}};

assign shl_ln73_5_fu_770_p1 = ap_port_reg_data_5_val;

assign shl_ln73_5_fu_770_p3 = {{shl_ln73_5_fu_770_p1}, {2'd0}};

assign shl_ln_fu_608_p1 = data_0_val;

assign shl_ln_fu_608_p3 = {{shl_ln_fu_608_p1}, {8'd0}};

assign trunc_ln42_11_fu_812_p1 = grp_fu_202_p2;

assign trunc_ln42_18_fu_882_p1 = grp_fu_207_p2;

assign trunc_ln42_19_fu_892_p1 = grp_fu_204_p2;

assign trunc_ln42_5_fu_713_p1 = grp_fu_204_p2;

assign trunc_ln42_7_fu_788_p4 = {{add_ln73_2_fu_782_p2[22:10]}};

assign trunc_ln42_s_fu_638_p4 = {{add_ln73_fu_632_p2[24:10]}};

assign trunc_ln_fu_594_p1 = grp_fu_205_p2;

assign trunc_ln_fu_594_p4 = {{trunc_ln_fu_594_p1[24:10]}};

endmodule //myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s
