-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config5_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_3_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_4_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_5_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_6_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_7_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_8_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_9_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_10_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_11_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config5_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal icmp_ln45_fu_160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_11_fu_156_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_fu_166_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_1_fu_178_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_10_fu_152_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_1_fu_184_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_2_fu_196_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_9_fu_148_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_2_fu_202_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_3_fu_214_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_8_fu_144_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_3_fu_220_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_4_fu_232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_7_fu_140_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_4_fu_238_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_5_fu_250_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_6_fu_136_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_5_fu_256_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_6_fu_268_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_5_fu_132_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_6_fu_274_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_7_fu_286_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_4_fu_128_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_7_fu_292_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_8_fu_304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_3_fu_124_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_8_fu_310_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_9_fu_322_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_2_fu_120_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_9_fu_328_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_10_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_1_fu_116_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_10_fu_346_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_11_fu_358_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_fu_112_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_11_fu_364_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln45_fu_174_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_1_fu_192_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_2_fu_210_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_3_fu_228_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_4_fu_246_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_5_fu_264_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_6_fu_282_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_7_fu_300_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_8_fu_318_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_9_fu_336_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_10_fu_354_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_11_fu_372_p1 : STD_LOGIC_VECTOR (15 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= zext_ln45_fu_174_p1;
    ap_return_1 <= zext_ln45_1_fu_192_p1;
    ap_return_10 <= zext_ln45_10_fu_354_p1;
    ap_return_11 <= zext_ln45_11_fu_372_p1;
    ap_return_2 <= zext_ln45_2_fu_210_p1;
    ap_return_3 <= zext_ln45_3_fu_228_p1;
    ap_return_4 <= zext_ln45_4_fu_246_p1;
    ap_return_5 <= zext_ln45_5_fu_264_p1;
    ap_return_6 <= zext_ln45_6_fu_282_p1;
    ap_return_7 <= zext_ln45_7_fu_300_p1;
    ap_return_8 <= zext_ln45_8_fu_318_p1;
    ap_return_9 <= zext_ln45_9_fu_336_p1;
    datareg_10_fu_346_p3 <= 
        trunc_ln42_1_fu_116_p1 when (icmp_ln45_10_fu_340_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_11_fu_364_p3 <= 
        trunc_ln42_fu_112_p1 when (icmp_ln45_11_fu_358_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_1_fu_184_p3 <= 
        trunc_ln42_10_fu_152_p1 when (icmp_ln45_1_fu_178_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_2_fu_202_p3 <= 
        trunc_ln42_9_fu_148_p1 when (icmp_ln45_2_fu_196_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_3_fu_220_p3 <= 
        trunc_ln42_8_fu_144_p1 when (icmp_ln45_3_fu_214_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_4_fu_238_p3 <= 
        trunc_ln42_7_fu_140_p1 when (icmp_ln45_4_fu_232_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_5_fu_256_p3 <= 
        trunc_ln42_6_fu_136_p1 when (icmp_ln45_5_fu_250_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_6_fu_274_p3 <= 
        trunc_ln42_5_fu_132_p1 when (icmp_ln45_6_fu_268_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_7_fu_292_p3 <= 
        trunc_ln42_4_fu_128_p1 when (icmp_ln45_7_fu_286_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_8_fu_310_p3 <= 
        trunc_ln42_3_fu_124_p1 when (icmp_ln45_8_fu_304_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_9_fu_328_p3 <= 
        trunc_ln42_2_fu_120_p1 when (icmp_ln45_9_fu_322_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_fu_166_p3 <= 
        trunc_ln42_11_fu_156_p1 when (icmp_ln45_fu_160_p2(0) = '1') else 
        ap_const_lv15_0;
    icmp_ln45_10_fu_340_p2 <= "1" when (signed(data_10_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_11_fu_358_p2 <= "1" when (signed(data_11_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_1_fu_178_p2 <= "1" when (signed(data_1_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_2_fu_196_p2 <= "1" when (signed(data_2_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_3_fu_214_p2 <= "1" when (signed(data_3_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_4_fu_232_p2 <= "1" when (signed(data_4_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_5_fu_250_p2 <= "1" when (signed(data_5_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_6_fu_268_p2 <= "1" when (signed(data_6_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_7_fu_286_p2 <= "1" when (signed(data_7_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_8_fu_304_p2 <= "1" when (signed(data_8_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_9_fu_322_p2 <= "1" when (signed(data_9_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_fu_160_p2 <= "1" when (signed(data_0_val) > signed(ap_const_lv16_0)) else "0";
    trunc_ln42_10_fu_152_p1 <= data_1_val(15 - 1 downto 0);
    trunc_ln42_11_fu_156_p1 <= data_0_val(15 - 1 downto 0);
    trunc_ln42_1_fu_116_p1 <= data_10_val(15 - 1 downto 0);
    trunc_ln42_2_fu_120_p1 <= data_9_val(15 - 1 downto 0);
    trunc_ln42_3_fu_124_p1 <= data_8_val(15 - 1 downto 0);
    trunc_ln42_4_fu_128_p1 <= data_7_val(15 - 1 downto 0);
    trunc_ln42_5_fu_132_p1 <= data_6_val(15 - 1 downto 0);
    trunc_ln42_6_fu_136_p1 <= data_5_val(15 - 1 downto 0);
    trunc_ln42_7_fu_140_p1 <= data_4_val(15 - 1 downto 0);
    trunc_ln42_8_fu_144_p1 <= data_3_val(15 - 1 downto 0);
    trunc_ln42_9_fu_148_p1 <= data_2_val(15 - 1 downto 0);
    trunc_ln42_fu_112_p1 <= data_11_val(15 - 1 downto 0);
    zext_ln45_10_fu_354_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_10_fu_346_p3),16));
    zext_ln45_11_fu_372_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_11_fu_364_p3),16));
    zext_ln45_1_fu_192_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_1_fu_184_p3),16));
    zext_ln45_2_fu_210_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_2_fu_202_p3),16));
    zext_ln45_3_fu_228_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_3_fu_220_p3),16));
    zext_ln45_4_fu_246_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_4_fu_238_p3),16));
    zext_ln45_5_fu_264_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_5_fu_256_p3),16));
    zext_ln45_6_fu_282_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_6_fu_274_p3),16));
    zext_ln45_7_fu_300_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_7_fu_292_p3),16));
    zext_ln45_8_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_8_fu_310_p3),16));
    zext_ln45_9_fu_336_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_9_fu_328_p3),16));
    zext_ln45_fu_174_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_fu_166_p3),16));
end behav;
