-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_3_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_4_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_5_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_6_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_7_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_8_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_9_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_10_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_11_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_12_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_13_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_14_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_15_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_16_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_17_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_18_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_19_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_20_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_21_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_22_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_23_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_17 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_18 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_19 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_20 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_21 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_22 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_23 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal icmp_ln45_fu_304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_34_fu_300_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_fu_310_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_12_fu_322_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_33_fu_296_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_12_fu_328_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_13_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_32_fu_292_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_13_fu_346_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_14_fu_358_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_31_fu_288_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_14_fu_364_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_15_fu_376_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_30_fu_284_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_15_fu_382_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_16_fu_394_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_29_fu_280_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_16_fu_400_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_17_fu_412_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_28_fu_276_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_17_fu_418_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_18_fu_430_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_27_fu_272_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_18_fu_436_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_19_fu_448_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_26_fu_268_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_19_fu_454_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_20_fu_466_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_25_fu_264_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_20_fu_472_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_21_fu_484_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_24_fu_260_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_21_fu_490_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_22_fu_502_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_23_fu_256_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_22_fu_508_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_23_fu_520_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_22_fu_252_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_23_fu_526_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_24_fu_538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_21_fu_248_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_24_fu_544_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_25_fu_556_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_20_fu_244_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_25_fu_562_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_26_fu_574_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_19_fu_240_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_26_fu_580_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_27_fu_592_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_18_fu_236_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_27_fu_598_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_28_fu_610_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_17_fu_232_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_28_fu_616_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_29_fu_628_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_16_fu_228_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_29_fu_634_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_30_fu_646_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_15_fu_224_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_30_fu_652_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_31_fu_664_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_14_fu_220_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_31_fu_670_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_32_fu_682_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_13_fu_216_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_32_fu_688_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_33_fu_700_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_12_fu_212_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_33_fu_706_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_34_fu_718_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_fu_208_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_34_fu_724_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln45_fu_318_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_12_fu_336_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_13_fu_354_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_14_fu_372_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_15_fu_390_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_16_fu_408_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_17_fu_426_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_18_fu_444_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_19_fu_462_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_20_fu_480_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_21_fu_498_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_22_fu_516_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_23_fu_534_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_24_fu_552_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_25_fu_570_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_26_fu_588_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_27_fu_606_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_28_fu_624_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_29_fu_642_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_30_fu_660_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_31_fu_678_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_32_fu_696_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_33_fu_714_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_34_fu_732_p1 : STD_LOGIC_VECTOR (15 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= zext_ln45_fu_318_p1;
    ap_return_1 <= zext_ln45_12_fu_336_p1;
    ap_return_10 <= zext_ln45_21_fu_498_p1;
    ap_return_11 <= zext_ln45_22_fu_516_p1;
    ap_return_12 <= zext_ln45_23_fu_534_p1;
    ap_return_13 <= zext_ln45_24_fu_552_p1;
    ap_return_14 <= zext_ln45_25_fu_570_p1;
    ap_return_15 <= zext_ln45_26_fu_588_p1;
    ap_return_16 <= zext_ln45_27_fu_606_p1;
    ap_return_17 <= zext_ln45_28_fu_624_p1;
    ap_return_18 <= zext_ln45_29_fu_642_p1;
    ap_return_19 <= zext_ln45_30_fu_660_p1;
    ap_return_2 <= zext_ln45_13_fu_354_p1;
    ap_return_20 <= zext_ln45_31_fu_678_p1;
    ap_return_21 <= zext_ln45_32_fu_696_p1;
    ap_return_22 <= zext_ln45_33_fu_714_p1;
    ap_return_23 <= zext_ln45_34_fu_732_p1;
    ap_return_3 <= zext_ln45_14_fu_372_p1;
    ap_return_4 <= zext_ln45_15_fu_390_p1;
    ap_return_5 <= zext_ln45_16_fu_408_p1;
    ap_return_6 <= zext_ln45_17_fu_426_p1;
    ap_return_7 <= zext_ln45_18_fu_444_p1;
    ap_return_8 <= zext_ln45_19_fu_462_p1;
    ap_return_9 <= zext_ln45_20_fu_480_p1;
    datareg_12_fu_328_p3 <= 
        trunc_ln42_33_fu_296_p1 when (icmp_ln45_12_fu_322_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_13_fu_346_p3 <= 
        trunc_ln42_32_fu_292_p1 when (icmp_ln45_13_fu_340_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_14_fu_364_p3 <= 
        trunc_ln42_31_fu_288_p1 when (icmp_ln45_14_fu_358_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_15_fu_382_p3 <= 
        trunc_ln42_30_fu_284_p1 when (icmp_ln45_15_fu_376_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_16_fu_400_p3 <= 
        trunc_ln42_29_fu_280_p1 when (icmp_ln45_16_fu_394_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_17_fu_418_p3 <= 
        trunc_ln42_28_fu_276_p1 when (icmp_ln45_17_fu_412_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_18_fu_436_p3 <= 
        trunc_ln42_27_fu_272_p1 when (icmp_ln45_18_fu_430_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_19_fu_454_p3 <= 
        trunc_ln42_26_fu_268_p1 when (icmp_ln45_19_fu_448_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_20_fu_472_p3 <= 
        trunc_ln42_25_fu_264_p1 when (icmp_ln45_20_fu_466_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_21_fu_490_p3 <= 
        trunc_ln42_24_fu_260_p1 when (icmp_ln45_21_fu_484_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_22_fu_508_p3 <= 
        trunc_ln42_23_fu_256_p1 when (icmp_ln45_22_fu_502_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_23_fu_526_p3 <= 
        trunc_ln42_22_fu_252_p1 when (icmp_ln45_23_fu_520_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_24_fu_544_p3 <= 
        trunc_ln42_21_fu_248_p1 when (icmp_ln45_24_fu_538_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_25_fu_562_p3 <= 
        trunc_ln42_20_fu_244_p1 when (icmp_ln45_25_fu_556_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_26_fu_580_p3 <= 
        trunc_ln42_19_fu_240_p1 when (icmp_ln45_26_fu_574_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_27_fu_598_p3 <= 
        trunc_ln42_18_fu_236_p1 when (icmp_ln45_27_fu_592_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_28_fu_616_p3 <= 
        trunc_ln42_17_fu_232_p1 when (icmp_ln45_28_fu_610_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_29_fu_634_p3 <= 
        trunc_ln42_16_fu_228_p1 when (icmp_ln45_29_fu_628_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_30_fu_652_p3 <= 
        trunc_ln42_15_fu_224_p1 when (icmp_ln45_30_fu_646_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_31_fu_670_p3 <= 
        trunc_ln42_14_fu_220_p1 when (icmp_ln45_31_fu_664_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_32_fu_688_p3 <= 
        trunc_ln42_13_fu_216_p1 when (icmp_ln45_32_fu_682_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_33_fu_706_p3 <= 
        trunc_ln42_12_fu_212_p1 when (icmp_ln45_33_fu_700_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_34_fu_724_p3 <= 
        trunc_ln42_fu_208_p1 when (icmp_ln45_34_fu_718_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_fu_310_p3 <= 
        trunc_ln42_34_fu_300_p1 when (icmp_ln45_fu_304_p2(0) = '1') else 
        ap_const_lv15_0;
    icmp_ln45_12_fu_322_p2 <= "1" when (signed(data_1_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_13_fu_340_p2 <= "1" when (signed(data_2_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_14_fu_358_p2 <= "1" when (signed(data_3_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_15_fu_376_p2 <= "1" when (signed(data_4_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_16_fu_394_p2 <= "1" when (signed(data_5_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_17_fu_412_p2 <= "1" when (signed(data_6_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_18_fu_430_p2 <= "1" when (signed(data_7_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_19_fu_448_p2 <= "1" when (signed(data_8_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_20_fu_466_p2 <= "1" when (signed(data_9_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_21_fu_484_p2 <= "1" when (signed(data_10_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_22_fu_502_p2 <= "1" when (signed(data_11_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_23_fu_520_p2 <= "1" when (signed(data_12_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_24_fu_538_p2 <= "1" when (signed(data_13_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_25_fu_556_p2 <= "1" when (signed(data_14_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_26_fu_574_p2 <= "1" when (signed(data_15_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_27_fu_592_p2 <= "1" when (signed(data_16_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_28_fu_610_p2 <= "1" when (signed(data_17_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_29_fu_628_p2 <= "1" when (signed(data_18_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_30_fu_646_p2 <= "1" when (signed(data_19_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_31_fu_664_p2 <= "1" when (signed(data_20_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_32_fu_682_p2 <= "1" when (signed(data_21_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_33_fu_700_p2 <= "1" when (signed(data_22_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_34_fu_718_p2 <= "1" when (signed(data_23_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_fu_304_p2 <= "1" when (signed(data_0_val) > signed(ap_const_lv16_0)) else "0";
    trunc_ln42_12_fu_212_p1 <= data_22_val(15 - 1 downto 0);
    trunc_ln42_13_fu_216_p1 <= data_21_val(15 - 1 downto 0);
    trunc_ln42_14_fu_220_p1 <= data_20_val(15 - 1 downto 0);
    trunc_ln42_15_fu_224_p1 <= data_19_val(15 - 1 downto 0);
    trunc_ln42_16_fu_228_p1 <= data_18_val(15 - 1 downto 0);
    trunc_ln42_17_fu_232_p1 <= data_17_val(15 - 1 downto 0);
    trunc_ln42_18_fu_236_p1 <= data_16_val(15 - 1 downto 0);
    trunc_ln42_19_fu_240_p1 <= data_15_val(15 - 1 downto 0);
    trunc_ln42_20_fu_244_p1 <= data_14_val(15 - 1 downto 0);
    trunc_ln42_21_fu_248_p1 <= data_13_val(15 - 1 downto 0);
    trunc_ln42_22_fu_252_p1 <= data_12_val(15 - 1 downto 0);
    trunc_ln42_23_fu_256_p1 <= data_11_val(15 - 1 downto 0);
    trunc_ln42_24_fu_260_p1 <= data_10_val(15 - 1 downto 0);
    trunc_ln42_25_fu_264_p1 <= data_9_val(15 - 1 downto 0);
    trunc_ln42_26_fu_268_p1 <= data_8_val(15 - 1 downto 0);
    trunc_ln42_27_fu_272_p1 <= data_7_val(15 - 1 downto 0);
    trunc_ln42_28_fu_276_p1 <= data_6_val(15 - 1 downto 0);
    trunc_ln42_29_fu_280_p1 <= data_5_val(15 - 1 downto 0);
    trunc_ln42_30_fu_284_p1 <= data_4_val(15 - 1 downto 0);
    trunc_ln42_31_fu_288_p1 <= data_3_val(15 - 1 downto 0);
    trunc_ln42_32_fu_292_p1 <= data_2_val(15 - 1 downto 0);
    trunc_ln42_33_fu_296_p1 <= data_1_val(15 - 1 downto 0);
    trunc_ln42_34_fu_300_p1 <= data_0_val(15 - 1 downto 0);
    trunc_ln42_fu_208_p1 <= data_23_val(15 - 1 downto 0);
    zext_ln45_12_fu_336_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_12_fu_328_p3),16));
    zext_ln45_13_fu_354_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_13_fu_346_p3),16));
    zext_ln45_14_fu_372_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_14_fu_364_p3),16));
    zext_ln45_15_fu_390_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_15_fu_382_p3),16));
    zext_ln45_16_fu_408_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_16_fu_400_p3),16));
    zext_ln45_17_fu_426_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_17_fu_418_p3),16));
    zext_ln45_18_fu_444_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_18_fu_436_p3),16));
    zext_ln45_19_fu_462_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_19_fu_454_p3),16));
    zext_ln45_20_fu_480_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_20_fu_472_p3),16));
    zext_ln45_21_fu_498_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_21_fu_490_p3),16));
    zext_ln45_22_fu_516_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_22_fu_508_p3),16));
    zext_ln45_23_fu_534_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_23_fu_526_p3),16));
    zext_ln45_24_fu_552_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_24_fu_544_p3),16));
    zext_ln45_25_fu_570_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_25_fu_562_p3),16));
    zext_ln45_26_fu_588_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_26_fu_580_p3),16));
    zext_ln45_27_fu_606_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_27_fu_598_p3),16));
    zext_ln45_28_fu_624_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_28_fu_616_p3),16));
    zext_ln45_29_fu_642_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_29_fu_634_p3),16));
    zext_ln45_30_fu_660_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_30_fu_652_p3),16));
    zext_ln45_31_fu_678_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_31_fu_670_p3),16));
    zext_ln45_32_fu_696_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_32_fu_688_p3),16));
    zext_ln45_33_fu_714_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_33_fu_706_p3),16));
    zext_ln45_34_fu_732_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_34_fu_724_p3),16));
    zext_ln45_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_fu_310_p3),16));
end behav;
