// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s (
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        data_16_val,
        data_17_val,
        data_18_val,
        data_19_val,
        data_20_val,
        data_21_val,
        data_22_val,
        data_23_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23
);


output   ap_ready;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
input  [15:0] data_5_val;
input  [15:0] data_6_val;
input  [15:0] data_7_val;
input  [15:0] data_8_val;
input  [15:0] data_9_val;
input  [15:0] data_10_val;
input  [15:0] data_11_val;
input  [15:0] data_12_val;
input  [15:0] data_13_val;
input  [15:0] data_14_val;
input  [15:0] data_15_val;
input  [15:0] data_16_val;
input  [15:0] data_17_val;
input  [15:0] data_18_val;
input  [15:0] data_19_val;
input  [15:0] data_20_val;
input  [15:0] data_21_val;
input  [15:0] data_22_val;
input  [15:0] data_23_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;
output  [15:0] ap_return_16;
output  [15:0] ap_return_17;
output  [15:0] ap_return_18;
output  [15:0] ap_return_19;
output  [15:0] ap_return_20;
output  [15:0] ap_return_21;
output  [15:0] ap_return_22;
output  [15:0] ap_return_23;

wire   [0:0] icmp_ln45_fu_304_p2;
wire   [14:0] trunc_ln42_34_fu_300_p1;
wire   [14:0] datareg_fu_310_p3;
wire   [0:0] icmp_ln45_12_fu_322_p2;
wire   [14:0] trunc_ln42_33_fu_296_p1;
wire   [14:0] datareg_12_fu_328_p3;
wire   [0:0] icmp_ln45_13_fu_340_p2;
wire   [14:0] trunc_ln42_32_fu_292_p1;
wire   [14:0] datareg_13_fu_346_p3;
wire   [0:0] icmp_ln45_14_fu_358_p2;
wire   [14:0] trunc_ln42_31_fu_288_p1;
wire   [14:0] datareg_14_fu_364_p3;
wire   [0:0] icmp_ln45_15_fu_376_p2;
wire   [14:0] trunc_ln42_30_fu_284_p1;
wire   [14:0] datareg_15_fu_382_p3;
wire   [0:0] icmp_ln45_16_fu_394_p2;
wire   [14:0] trunc_ln42_29_fu_280_p1;
wire   [14:0] datareg_16_fu_400_p3;
wire   [0:0] icmp_ln45_17_fu_412_p2;
wire   [14:0] trunc_ln42_28_fu_276_p1;
wire   [14:0] datareg_17_fu_418_p3;
wire   [0:0] icmp_ln45_18_fu_430_p2;
wire   [14:0] trunc_ln42_27_fu_272_p1;
wire   [14:0] datareg_18_fu_436_p3;
wire   [0:0] icmp_ln45_19_fu_448_p2;
wire   [14:0] trunc_ln42_26_fu_268_p1;
wire   [14:0] datareg_19_fu_454_p3;
wire   [0:0] icmp_ln45_20_fu_466_p2;
wire   [14:0] trunc_ln42_25_fu_264_p1;
wire   [14:0] datareg_20_fu_472_p3;
wire   [0:0] icmp_ln45_21_fu_484_p2;
wire   [14:0] trunc_ln42_24_fu_260_p1;
wire   [14:0] datareg_21_fu_490_p3;
wire   [0:0] icmp_ln45_22_fu_502_p2;
wire   [14:0] trunc_ln42_23_fu_256_p1;
wire   [14:0] datareg_22_fu_508_p3;
wire   [0:0] icmp_ln45_23_fu_520_p2;
wire   [14:0] trunc_ln42_22_fu_252_p1;
wire   [14:0] datareg_23_fu_526_p3;
wire   [0:0] icmp_ln45_24_fu_538_p2;
wire   [14:0] trunc_ln42_21_fu_248_p1;
wire   [14:0] datareg_24_fu_544_p3;
wire   [0:0] icmp_ln45_25_fu_556_p2;
wire   [14:0] trunc_ln42_20_fu_244_p1;
wire   [14:0] datareg_25_fu_562_p3;
wire   [0:0] icmp_ln45_26_fu_574_p2;
wire   [14:0] trunc_ln42_19_fu_240_p1;
wire   [14:0] datareg_26_fu_580_p3;
wire   [0:0] icmp_ln45_27_fu_592_p2;
wire   [14:0] trunc_ln42_18_fu_236_p1;
wire   [14:0] datareg_27_fu_598_p3;
wire   [0:0] icmp_ln45_28_fu_610_p2;
wire   [14:0] trunc_ln42_17_fu_232_p1;
wire   [14:0] datareg_28_fu_616_p3;
wire   [0:0] icmp_ln45_29_fu_628_p2;
wire   [14:0] trunc_ln42_16_fu_228_p1;
wire   [14:0] datareg_29_fu_634_p3;
wire   [0:0] icmp_ln45_30_fu_646_p2;
wire   [14:0] trunc_ln42_15_fu_224_p1;
wire   [14:0] datareg_30_fu_652_p3;
wire   [0:0] icmp_ln45_31_fu_664_p2;
wire   [14:0] trunc_ln42_14_fu_220_p1;
wire   [14:0] datareg_31_fu_670_p3;
wire   [0:0] icmp_ln45_32_fu_682_p2;
wire   [14:0] trunc_ln42_13_fu_216_p1;
wire   [14:0] datareg_32_fu_688_p3;
wire   [0:0] icmp_ln45_33_fu_700_p2;
wire   [14:0] trunc_ln42_12_fu_212_p1;
wire   [14:0] datareg_33_fu_706_p3;
wire   [0:0] icmp_ln45_34_fu_718_p2;
wire   [14:0] trunc_ln42_fu_208_p1;
wire   [14:0] datareg_34_fu_724_p3;
wire   [15:0] zext_ln45_fu_318_p1;
wire   [15:0] zext_ln45_12_fu_336_p1;
wire   [15:0] zext_ln45_13_fu_354_p1;
wire   [15:0] zext_ln45_14_fu_372_p1;
wire   [15:0] zext_ln45_15_fu_390_p1;
wire   [15:0] zext_ln45_16_fu_408_p1;
wire   [15:0] zext_ln45_17_fu_426_p1;
wire   [15:0] zext_ln45_18_fu_444_p1;
wire   [15:0] zext_ln45_19_fu_462_p1;
wire   [15:0] zext_ln45_20_fu_480_p1;
wire   [15:0] zext_ln45_21_fu_498_p1;
wire   [15:0] zext_ln45_22_fu_516_p1;
wire   [15:0] zext_ln45_23_fu_534_p1;
wire   [15:0] zext_ln45_24_fu_552_p1;
wire   [15:0] zext_ln45_25_fu_570_p1;
wire   [15:0] zext_ln45_26_fu_588_p1;
wire   [15:0] zext_ln45_27_fu_606_p1;
wire   [15:0] zext_ln45_28_fu_624_p1;
wire   [15:0] zext_ln45_29_fu_642_p1;
wire   [15:0] zext_ln45_30_fu_660_p1;
wire   [15:0] zext_ln45_31_fu_678_p1;
wire   [15:0] zext_ln45_32_fu_696_p1;
wire   [15:0] zext_ln45_33_fu_714_p1;
wire   [15:0] zext_ln45_34_fu_732_p1;

assign ap_ready = 1'b1;

assign datareg_12_fu_328_p3 = ((icmp_ln45_12_fu_322_p2[0:0] == 1'b1) ? trunc_ln42_33_fu_296_p1 : 15'd0);

assign datareg_13_fu_346_p3 = ((icmp_ln45_13_fu_340_p2[0:0] == 1'b1) ? trunc_ln42_32_fu_292_p1 : 15'd0);

assign datareg_14_fu_364_p3 = ((icmp_ln45_14_fu_358_p2[0:0] == 1'b1) ? trunc_ln42_31_fu_288_p1 : 15'd0);

assign datareg_15_fu_382_p3 = ((icmp_ln45_15_fu_376_p2[0:0] == 1'b1) ? trunc_ln42_30_fu_284_p1 : 15'd0);

assign datareg_16_fu_400_p3 = ((icmp_ln45_16_fu_394_p2[0:0] == 1'b1) ? trunc_ln42_29_fu_280_p1 : 15'd0);

assign datareg_17_fu_418_p3 = ((icmp_ln45_17_fu_412_p2[0:0] == 1'b1) ? trunc_ln42_28_fu_276_p1 : 15'd0);

assign datareg_18_fu_436_p3 = ((icmp_ln45_18_fu_430_p2[0:0] == 1'b1) ? trunc_ln42_27_fu_272_p1 : 15'd0);

assign datareg_19_fu_454_p3 = ((icmp_ln45_19_fu_448_p2[0:0] == 1'b1) ? trunc_ln42_26_fu_268_p1 : 15'd0);

assign datareg_20_fu_472_p3 = ((icmp_ln45_20_fu_466_p2[0:0] == 1'b1) ? trunc_ln42_25_fu_264_p1 : 15'd0);

assign datareg_21_fu_490_p3 = ((icmp_ln45_21_fu_484_p2[0:0] == 1'b1) ? trunc_ln42_24_fu_260_p1 : 15'd0);

assign datareg_22_fu_508_p3 = ((icmp_ln45_22_fu_502_p2[0:0] == 1'b1) ? trunc_ln42_23_fu_256_p1 : 15'd0);

assign datareg_23_fu_526_p3 = ((icmp_ln45_23_fu_520_p2[0:0] == 1'b1) ? trunc_ln42_22_fu_252_p1 : 15'd0);

assign datareg_24_fu_544_p3 = ((icmp_ln45_24_fu_538_p2[0:0] == 1'b1) ? trunc_ln42_21_fu_248_p1 : 15'd0);

assign datareg_25_fu_562_p3 = ((icmp_ln45_25_fu_556_p2[0:0] == 1'b1) ? trunc_ln42_20_fu_244_p1 : 15'd0);

assign datareg_26_fu_580_p3 = ((icmp_ln45_26_fu_574_p2[0:0] == 1'b1) ? trunc_ln42_19_fu_240_p1 : 15'd0);

assign datareg_27_fu_598_p3 = ((icmp_ln45_27_fu_592_p2[0:0] == 1'b1) ? trunc_ln42_18_fu_236_p1 : 15'd0);

assign datareg_28_fu_616_p3 = ((icmp_ln45_28_fu_610_p2[0:0] == 1'b1) ? trunc_ln42_17_fu_232_p1 : 15'd0);

assign datareg_29_fu_634_p3 = ((icmp_ln45_29_fu_628_p2[0:0] == 1'b1) ? trunc_ln42_16_fu_228_p1 : 15'd0);

assign datareg_30_fu_652_p3 = ((icmp_ln45_30_fu_646_p2[0:0] == 1'b1) ? trunc_ln42_15_fu_224_p1 : 15'd0);

assign datareg_31_fu_670_p3 = ((icmp_ln45_31_fu_664_p2[0:0] == 1'b1) ? trunc_ln42_14_fu_220_p1 : 15'd0);

assign datareg_32_fu_688_p3 = ((icmp_ln45_32_fu_682_p2[0:0] == 1'b1) ? trunc_ln42_13_fu_216_p1 : 15'd0);

assign datareg_33_fu_706_p3 = ((icmp_ln45_33_fu_700_p2[0:0] == 1'b1) ? trunc_ln42_12_fu_212_p1 : 15'd0);

assign datareg_34_fu_724_p3 = ((icmp_ln45_34_fu_718_p2[0:0] == 1'b1) ? trunc_ln42_fu_208_p1 : 15'd0);

assign datareg_fu_310_p3 = ((icmp_ln45_fu_304_p2[0:0] == 1'b1) ? trunc_ln42_34_fu_300_p1 : 15'd0);

assign trunc_ln42_12_fu_212_p1 = data_22_val[14:0];

assign trunc_ln42_13_fu_216_p1 = data_21_val[14:0];

assign trunc_ln42_14_fu_220_p1 = data_20_val[14:0];

assign trunc_ln42_15_fu_224_p1 = data_19_val[14:0];

assign trunc_ln42_16_fu_228_p1 = data_18_val[14:0];

assign trunc_ln42_17_fu_232_p1 = data_17_val[14:0];

assign trunc_ln42_18_fu_236_p1 = data_16_val[14:0];

assign trunc_ln42_19_fu_240_p1 = data_15_val[14:0];

assign trunc_ln42_20_fu_244_p1 = data_14_val[14:0];

assign trunc_ln42_21_fu_248_p1 = data_13_val[14:0];

assign trunc_ln42_22_fu_252_p1 = data_12_val[14:0];

assign trunc_ln42_23_fu_256_p1 = data_11_val[14:0];

assign trunc_ln42_24_fu_260_p1 = data_10_val[14:0];

assign trunc_ln42_25_fu_264_p1 = data_9_val[14:0];

assign trunc_ln42_26_fu_268_p1 = data_8_val[14:0];

assign trunc_ln42_27_fu_272_p1 = data_7_val[14:0];

assign trunc_ln42_28_fu_276_p1 = data_6_val[14:0];

assign trunc_ln42_29_fu_280_p1 = data_5_val[14:0];

assign trunc_ln42_30_fu_284_p1 = data_4_val[14:0];

assign trunc_ln42_31_fu_288_p1 = data_3_val[14:0];

assign trunc_ln42_32_fu_292_p1 = data_2_val[14:0];

assign trunc_ln42_33_fu_296_p1 = data_1_val[14:0];

assign trunc_ln42_34_fu_300_p1 = data_0_val[14:0];

assign trunc_ln42_fu_208_p1 = data_23_val[14:0];

assign zext_ln45_12_fu_336_p1 = datareg_12_fu_328_p3;

assign zext_ln45_13_fu_354_p1 = datareg_13_fu_346_p3;

assign zext_ln45_14_fu_372_p1 = datareg_14_fu_364_p3;

assign zext_ln45_15_fu_390_p1 = datareg_15_fu_382_p3;

assign zext_ln45_16_fu_408_p1 = datareg_16_fu_400_p3;

assign zext_ln45_17_fu_426_p1 = datareg_17_fu_418_p3;

assign zext_ln45_18_fu_444_p1 = datareg_18_fu_436_p3;

assign zext_ln45_19_fu_462_p1 = datareg_19_fu_454_p3;

assign zext_ln45_20_fu_480_p1 = datareg_20_fu_472_p3;

assign zext_ln45_21_fu_498_p1 = datareg_21_fu_490_p3;

assign zext_ln45_22_fu_516_p1 = datareg_22_fu_508_p3;

assign zext_ln45_23_fu_534_p1 = datareg_23_fu_526_p3;

assign zext_ln45_24_fu_552_p1 = datareg_24_fu_544_p3;

assign zext_ln45_25_fu_570_p1 = datareg_25_fu_562_p3;

assign zext_ln45_26_fu_588_p1 = datareg_26_fu_580_p3;

assign zext_ln45_27_fu_606_p1 = datareg_27_fu_598_p3;

assign zext_ln45_28_fu_624_p1 = datareg_28_fu_616_p3;

assign zext_ln45_29_fu_642_p1 = datareg_29_fu_634_p3;

assign zext_ln45_30_fu_660_p1 = datareg_30_fu_652_p3;

assign zext_ln45_31_fu_678_p1 = datareg_31_fu_670_p3;

assign zext_ln45_32_fu_696_p1 = datareg_32_fu_688_p3;

assign zext_ln45_33_fu_714_p1 = datareg_33_fu_706_p3;

assign zext_ln45_34_fu_732_p1 = datareg_34_fu_724_p3;

assign zext_ln45_fu_318_p1 = datareg_fu_310_p3;

assign ap_return_0 = zext_ln45_fu_318_p1;

assign ap_return_1 = zext_ln45_12_fu_336_p1;

assign ap_return_10 = zext_ln45_21_fu_498_p1;

assign ap_return_11 = zext_ln45_22_fu_516_p1;

assign ap_return_12 = zext_ln45_23_fu_534_p1;

assign ap_return_13 = zext_ln45_24_fu_552_p1;

assign ap_return_14 = zext_ln45_25_fu_570_p1;

assign ap_return_15 = zext_ln45_26_fu_588_p1;

assign ap_return_16 = zext_ln45_27_fu_606_p1;

assign ap_return_17 = zext_ln45_28_fu_624_p1;

assign ap_return_18 = zext_ln45_29_fu_642_p1;

assign ap_return_19 = zext_ln45_30_fu_660_p1;

assign ap_return_2 = zext_ln45_13_fu_354_p1;

assign ap_return_20 = zext_ln45_31_fu_678_p1;

assign ap_return_21 = zext_ln45_32_fu_696_p1;

assign ap_return_22 = zext_ln45_33_fu_714_p1;

assign ap_return_23 = zext_ln45_34_fu_732_p1;

assign ap_return_3 = zext_ln45_14_fu_372_p1;

assign ap_return_4 = zext_ln45_15_fu_390_p1;

assign ap_return_5 = zext_ln45_16_fu_408_p1;

assign ap_return_6 = zext_ln45_17_fu_426_p1;

assign ap_return_7 = zext_ln45_18_fu_444_p1;

assign ap_return_8 = zext_ln45_19_fu_462_p1;

assign ap_return_9 = zext_ln45_20_fu_480_p1;

assign icmp_ln45_12_fu_322_p2 = (($signed(data_1_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_13_fu_340_p2 = (($signed(data_2_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_14_fu_358_p2 = (($signed(data_3_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_15_fu_376_p2 = (($signed(data_4_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_16_fu_394_p2 = (($signed(data_5_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_17_fu_412_p2 = (($signed(data_6_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_18_fu_430_p2 = (($signed(data_7_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_19_fu_448_p2 = (($signed(data_8_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_20_fu_466_p2 = (($signed(data_9_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_21_fu_484_p2 = (($signed(data_10_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_22_fu_502_p2 = (($signed(data_11_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_23_fu_520_p2 = (($signed(data_12_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_24_fu_538_p2 = (($signed(data_13_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_25_fu_556_p2 = (($signed(data_14_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_26_fu_574_p2 = (($signed(data_15_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_27_fu_592_p2 = (($signed(data_16_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_28_fu_610_p2 = (($signed(data_17_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_29_fu_628_p2 = (($signed(data_18_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_30_fu_646_p2 = (($signed(data_19_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_31_fu_664_p2 = (($signed(data_20_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_32_fu_682_p2 = (($signed(data_21_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_33_fu_700_p2 = (($signed(data_22_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_34_fu_718_p2 = (($signed(data_23_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_304_p2 = (($signed(data_0_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

endmodule //myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s
